s="have a nice day"
print(s)
print(s.upper())
print(s.title())
print(s.capitalize())
print(s.swapcase())
print(s.center(60))
print(s.center(60,"*"))
print(s.replace("nice", "good"))
print(s.find("nice"))
print(s.index("nice"))
print(s.count("a"))